In [1]:
import numpy as np

# Optimum Design Homework 3
Suppose you are given this data set: x=\[0.1, 0.9, 2.2, 3, 4.1, 5.2, 5.9, 6.8, 8.1, 8.7, 9.2, 11, 12.4, 14.1, 15.2, 16.8, 18.7, 19.9, 22\];    
y=\[28.5, 27, 29, 30.5, 37.3, 36.4, 32.4, 28.5, 30, 36.1, 39, 36, 32, 28, 22, 20, 27, 40, 61\]. 


In [2]:
x = np.array([0.1, 0.9, 2.2, 3, 4.1, 5.2, 5.9, 6.8, 8.1, 8.7, 9.2, 11, 12.4, 14.1, 15.2, 16.8, 18.7, 19.9, 22])
y = np.array([28.5, 27, 29, 30.5, 37.3, 36.4, 32.4, 28.5, 30, 36.1, 39, 36, 32, 28, 22, 20, 27, 40, 61])
print(f'x:{x}')
print(f'y:{y}')

x:[ 0.1  0.9  2.2  3.   4.1  5.2  5.9  6.8  8.1  8.7  9.2 11.  12.4 14.1
 15.2 16.8 18.7 19.9 22. ]
y:[28.5 27.  29.  30.5 37.3 36.4 32.4 28.5 30.  36.1 39.  36.  32.  28.
 22.  20.  27.  40.  61. ]


## 1.Find (analytically) the coefficients of the best-fit linear and quadratic regression equations.
### Linear regression

In [10]:
xx = np.sum(x**2)
xy = x.dot(y)
x_sum = np.sum(x)
y_sum = np.sum(y)
print(f'xx:{xx}')
print(f'xy:{xy}')
print(f'x_sum:{x_sum}')
print(f'y_sum:{y_sum}')

xx:2582.0499999999997
xy:6326.389999999999
x_sum:184.29999999999998
y_sum:620.7


In [14]:
n = x.size
print(f'Num of data points:{n}')

Num of data points:19


In [17]:
m = ( x_sum * y_sum - n * xy ) / ( x_sum ** 2 - n * xx )
b = ( y_sum - m * x_sum ) / n 
print(f'Best Fit coefficient m : {m}')
print(f'Best Fit coefficient b : {b}')

Best Fit coefficient m : 0.3847219074955303
Best Fit coefficient b : 28.936618549924937


### Quadratic Regression
f(x) = a_0 + a_1x + a_2x^2

In [36]:
row_1 = np.ones((19))
row_2 = x.reshape((19))
row_3 = (x**2).reshape(19)
print(row_1)
print(row_2)
print(row_3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0.1  0.9  2.2  3.   4.1  5.2  5.9  6.8  8.1  8.7  9.2 11.  12.4 14.1
 15.2 16.8 18.7 19.9 22. ]
[1.0000e-02 8.1000e-01 4.8400e+00 9.0000e+00 1.6810e+01 2.7040e+01
 3.4810e+01 4.6240e+01 6.5610e+01 7.5690e+01 8.4640e+01 1.2100e+02
 1.5376e+02 1.9881e+02 2.3104e+02 2.8224e+02 3.4969e+02 3.9601e+02
 4.8400e+02]


In [39]:
X = np.array([row_1, row_2, row_3]).T
print(X)

[[1.0000e+00 1.0000e-01 1.0000e-02]
 [1.0000e+00 9.0000e-01 8.1000e-01]
 [1.0000e+00 2.2000e+00 4.8400e+00]
 [1.0000e+00 3.0000e+00 9.0000e+00]
 [1.0000e+00 4.1000e+00 1.6810e+01]
 [1.0000e+00 5.2000e+00 2.7040e+01]
 [1.0000e+00 5.9000e+00 3.4810e+01]
 [1.0000e+00 6.8000e+00 4.6240e+01]
 [1.0000e+00 8.1000e+00 6.5610e+01]
 [1.0000e+00 8.7000e+00 7.5690e+01]
 [1.0000e+00 9.2000e+00 8.4640e+01]
 [1.0000e+00 1.1000e+01 1.2100e+02]
 [1.0000e+00 1.2400e+01 1.5376e+02]
 [1.0000e+00 1.4100e+01 1.9881e+02]
 [1.0000e+00 1.5200e+01 2.3104e+02]
 [1.0000e+00 1.6800e+01 2.8224e+02]
 [1.0000e+00 1.8700e+01 3.4969e+02]
 [1.0000e+00 1.9900e+01 3.9601e+02]
 [1.0000e+00 2.2000e+01 4.8400e+02]]


In [41]:
a = (np.linalg.inv(X.T @ X) @ X.T).dot(y)
print(f'Best fit coefficient : {a}')

Best fit coefficient : [33.84246993 -1.07117391  0.06781837]


## 2. Find the coefficients the best-fit linear and quadratic regression equations numerically. First, use Fletcher-Reeves conjugate gradient method. Then use one of the methods involving Newton’s method or one of the quasi-Newton methods (DFP or BFGS).